title:            Chewing the Cud
tagline:          "DIY Soylent in the UK"
description:      "A log of one man and his long-suffering girlfriend's experiences with making DIY soylent in the UK"
# Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://v2.theevilgenius.tk

# Owner/author information
owner:
  name:           Charles
  avatar:         bio-photo.jpg
  bio:            "Charles was captivated by the idea of Soylent and, when international orders were cancelled, decided to make his own and blog about it on the internet. When Charles is not putting strange substances into his body, he spends his days shining lasers at atoms, soldering things that have impedances and wondering why it doesn't work."
#  email:          hmfaysal@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        charlesbaynham
  facebook:       charlesbaynham90
  github:         charlesbaynham
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  # - title: The Evil-Genius
  #   url: http://www.theevilgenius.tk/
  #   external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter:    pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]